# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do
    clear_derived_data(derived_data_path: "DerivedData")
    cocoapods(try_repo_update_on_error: true)
    xcbuild(
      workspace: "Demo.xcworkspace",
      scheme: "Demo",
      configuration: "Debug",
      archive: true,
      destination: "generic/platform=iOS",
      build_settings: {
        "CODE_SIGNING_ALLOWED" => "NO",
        "CODE_SIGNING_REQUIRED" => "NO",
        "CODE_SIGN_IDENTITY" => ""
      },
      derivedDataPath: "DerivedData"
    )
  end
end
